[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
chrono = { version = "0.4.38", features = ["serde"] }
colored = "2.1.0"
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
